spring.datasource.url=${DB_URL:jdbc:oracle:thin:@localhost:1521:XE}
spring.datasource.username=${DB_USER:seu_usuario}
spring.datasource.password=${DB_PASSWORD:sua_senha}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
