INSERT INTO TB_CC_USUARIO (ID_USUARIO, NOME_USUARIO, EMAIL, SENHA, TP_PERFIL, DT_CADASTRO)
VALUES (1, 'Maria Silva', 'maria@email.com', 'senha123', 'TUTOR', CURRENT_DATE);

INSERT INTO TB_CC_PET (ID_PET, ID_USUARIO, NOME_PET, ESPECIE, DT_NASCIMENTO, DT_CADASTRO)
VALUES (1, 1, 'Thor', 'Cachorro', DATE '2020-05-10', CURRENT_DATE);

INSERT INTO TB_CC_CLINICA (ID_CLINICA, NOME_CLINICA, CNPJ, ENDERECO, TELEFONE)
VALUES (1, 'Clinica Pet Care', '12345678000199', 'Av. Paulista, 1000', '11999999999');
