INSERT INTO TB_CC_USUARIO (ID_USUARIO, NOME_USUARIO, EMAIL, SENHA, TP_PERFIL, DT_CADASTRO)
VALUES (1, 'Maria Silva', 'maria@email.com', 'senha123', 'TUTOR', CURRENT_DATE);

INSERT INTO TB_CC_PET (ID_PET, ID_USUARIO, NOME_PET, ESPECIE, DT_NASCIMENTO, DT_CADASTRO)
VALUES (1, 1, 'Thor', 'Cachorro', DATE '2020-05-10', CURRENT_DATE);

INSERT INTO TB_CC_CLINICA (ID_CLINICA, NOME_CLINICA, CNPJ, ENDERECO, TELEFONE)
VALUES (1, 'Clinica Pet Care', '12345678000199', 'Av. Paulista, 1000', '11999999999');

INSERT INTO TB_CC_PRESCRICAO (ID_PRESCRICAO, ID_PET, NOME_MEDICAMENTO, DS_DOSAGEM, FREQUENCIA_HORAS, DT_INICIO, DT_FIM)
VALUES (1, 1, 'Vermifugo', '1 comprimido', 24, CURRENT_DATE, DATEADD('DAY', 7, CURRENT_DATE));

INSERT INTO TB_CC_LOG_SAUDE (ID_LOG, ID_PET, DT_REGISTRO, VL_METRICA, METRICA, OBS)
VALUES (1, 1, CURRENT_TIMESTAMP, 38.5, 'temperatura', 'Controle rotineiro');

INSERT INTO TB_CC_AGENDAMENTO (ID_AGENDAMENTO, ID_PET, ID_CLINICA, DT_AGENDA, TIPO_SERVICO, STATUS)
VALUES (1, 1, 1, TIMESTAMP '2026-06-01 14:00:00', 'Consulta', 'AGENDADO');
