-- Cargas iniciais. Senhas em texto puro são recodificadas para BCrypt na subida da aplicação.
-- Inserts idempotentes: não falham se a carga já existir no Oracle da FIAP.

INSERT INTO TB_CC_USUARIO (ID_USUARIO, NOME_USUARIO, EMAIL, SENHA, TP_PERFIL, DT_CADASTRO)
SELECT SQ_CC_USUARIO.NEXTVAL, 'Maria Silva', 'maria@email.com', 'senha123', 'TUTOR', CURRENT_DATE
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_CC_USUARIO WHERE EMAIL = 'maria@email.com');

INSERT INTO TB_CC_USUARIO (ID_USUARIO, NOME_USUARIO, EMAIL, SENHA, TP_PERFIL, DT_CADASTRO)
SELECT SQ_CC_USUARIO.NEXTVAL, 'Carlos Mendes', 'carlos.vet@clyvo.com', 'senha123', 'VETERINARIO', CURRENT_DATE
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_CC_USUARIO WHERE EMAIL = 'carlos.vet@clyvo.com');

INSERT INTO TB_CC_PET (ID_PET, ID_USUARIO, NOME_PET, ESPECIE, DT_NASCIMENTO, DT_CADASTRO)
SELECT SQ_CC_PET.NEXTVAL, u.ID_USUARIO, 'Thor', 'Cachorro', DATE '2020-05-10', CURRENT_DATE
FROM TB_CC_USUARIO u
WHERE u.EMAIL = 'maria@email.com'
  AND NOT EXISTS (
      SELECT 1 FROM TB_CC_PET p
      WHERE p.NOME_PET = 'Thor' AND p.ID_USUARIO = u.ID_USUARIO
  );

INSERT INTO TB_CC_PET (ID_PET, ID_USUARIO, NOME_PET, ESPECIE, DT_NASCIMENTO, DT_CADASTRO)
SELECT SQ_CC_PET.NEXTVAL, u.ID_USUARIO, 'Luna', 'Gato', DATE '2022-02-14', CURRENT_DATE
FROM TB_CC_USUARIO u
WHERE u.EMAIL = 'maria@email.com'
  AND NOT EXISTS (
      SELECT 1 FROM TB_CC_PET p
      WHERE p.NOME_PET = 'Luna' AND p.ID_USUARIO = u.ID_USUARIO
  );

INSERT INTO TB_CC_CLINICA (ID_CLINICA, NOME_CLINICA, CNPJ, ENDERECO, TELEFONE)
SELECT SQ_CC_CLINICA.NEXTVAL, 'Clinica Pet Care', '12345678000199', 'Av. Paulista, 1000', '11999999999'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_CC_CLINICA WHERE CNPJ = '12345678000199');

INSERT INTO TB_CC_PRESCRICAO (ID_PRESCRICAO, ID_PET, NOME_MEDICAMENTO, DS_DOSAGEM, FREQUENCIA_HORAS, DT_INICIO, DT_FIM)
SELECT SQ_CC_PRESCRICAO.NEXTVAL, p.ID_PET, 'Vermifugo', '1 comprimido', 24, CURRENT_DATE, CURRENT_DATE + 7
FROM TB_CC_PET p
WHERE p.NOME_PET = 'Thor'
  AND NOT EXISTS (
      SELECT 1 FROM TB_CC_PRESCRICAO pr
      WHERE pr.ID_PET = p.ID_PET AND pr.NOME_MEDICAMENTO = 'Vermifugo'
  );

INSERT INTO TB_CC_LOG_SAUDE (ID_LOG, ID_PET, DT_REGISTRO, VL_METRICA, METRICA, OBS)
SELECT SQ_CC_LOG_SAUDE.NEXTVAL, p.ID_PET, CURRENT_TIMESTAMP, 12.40, 'peso', 'Controle rotineiro de peso'
FROM TB_CC_PET p
WHERE p.NOME_PET = 'Thor'
  AND NOT EXISTS (
      SELECT 1 FROM TB_CC_LOG_SAUDE l
      WHERE l.ID_PET = p.ID_PET AND l.METRICA = 'peso'
  );

INSERT INTO TB_CC_LOG_SAUDE (ID_LOG, ID_PET, DT_REGISTRO, VL_METRICA, METRICA, OBS)
SELECT SQ_CC_LOG_SAUDE.NEXTVAL, p.ID_PET, CURRENT_TIMESTAMP, 250, 'alimentacao', 'Racao diaria em gramas'
FROM TB_CC_PET p
WHERE p.NOME_PET = 'Thor'
  AND NOT EXISTS (
      SELECT 1 FROM TB_CC_LOG_SAUDE l
      WHERE l.ID_PET = p.ID_PET AND l.METRICA = 'alimentacao'
  );

INSERT INTO TB_CC_AGENDAMENTO (ID_AGENDAMENTO, ID_PET, ID_CLINICA, DT_AGENDA, TIPO_SERVICO, STATUS)
SELECT SQ_CC_AGENDAMENTO.NEXTVAL, p.ID_PET, c.ID_CLINICA, TIMESTAMP '2026-09-20 14:00:00', 'Consulta', 'AGENDADO'
FROM TB_CC_PET p
CROSS JOIN TB_CC_CLINICA c
WHERE p.NOME_PET = 'Thor'
  AND c.CNPJ = '12345678000199'
  AND NOT EXISTS (
      SELECT 1 FROM TB_CC_AGENDAMENTO a
      WHERE a.ID_PET = p.ID_PET AND a.ID_CLINICA = c.ID_CLINICA AND a.TIPO_SERVICO = 'Consulta'
  );
