-- Execute no Oracle se as sequences ainda nao existirem no banco FIAP.
-- Ajuste os nomes caso seu script de criacao use outra convencao.

CREATE SEQUENCE SQ_CC_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_CC_PET START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_CC_PRESCRICAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_CC_LOG_SAUDE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_CC_CLINICA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_CC_AGENDAMENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_CC_LOG_SISTEMA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
